{
 "title": "On-Demand EC2 Quotas",
 "tags": [
  "aws",
  "quota"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Standard Instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awsquota_ec2_on_demand_standard_count / awsquota_ec2_on_demand_standard_count_limit * 100"
    }
   ]
  },
  {
   "title": "F Instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awsquota_ec2_on_demand_f_count / awsquota_ec2_on_demand_f_count_limit * 100"
    }
   ]
  },
  {
   "title": "G instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awsquota_ec2_on_demand_g_count / awsquota_ec2_on_demand_g_count_limit * 100"
    }
   ]
  },
  {
   "title": "X instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awsquota_ec2_on_demand_x_count / awsquota_ec2_on_demand_x_count_limit * 100"
    }
   ]
  },
  {
   "title": "P instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awsquota_ec2_on_demand_p_count / awsquota_ec2_on_demand_p_count_limit * 100"
    }
   ]
  },
  {
   "title": "Inf instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awsquota_ec2_on_demand_inf_count / awsquota_ec2_on_demand_inf_count_limit * 100"
    }
   ]
  }
 ]
}