name: cd
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: setup python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
        with:
          python-version: "3.8"
      - name: install
        run: pip install .[dev]
      - name: build package
        run: python setup.py bdist_wheel
      - name: build docker image
        run: docker build . --tag gravitational/aws-quota-checker:test

  build_and_push_docker_image:
    runs-on: ubuntu-latest
    needs: [test]
    name: Build and push Docker image
    env:
      AWS_REGION: us-west-2
      AWS_ROLE: TBD
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: build docker image
        run: docker build . --tag gravitational/aws-quota-checker:staged
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE }}
      - name: login to ECR
        uses: aws-actions/amazon-ecr-login@2fc7aceee09e9e4a7105c0d060c656fad0b4f63d # v1
      - name: push docker image
        run: |
          docker tag gravitational/aws-quota-checker:staged gravitational/aws-quota-checker:${GITHUB_REF##*/}
          docker push gravitational/aws-quota-checker:${GITHUB_REF##*/}
