name: Dependency Review

on:
  pull_request:

jobs:
  dependency-review:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    uses: gravitational/shared-workflows/.github/workflows/dependency-review.yaml@main
    permissions:
      contents: read
